// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATQZCUWBtD6xeOgSOCK3vhFiXMv0eMLPs',
    appId: '1:398753978340:web:653aa514d43c9ac5d1d9f1',
    messagingSenderId: '398753978340',
    projectId: 'melon-d5a58',
    authDomain: 'melon-d5a58.firebaseapp.com',
    storageBucket: 'melon-d5a58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPprPzpu6wrlsQuPYNCEPmXZ3qmHbbH-w',
    appId: '1:398753978340:android:7f9317c153a85a0ad1d9f1',
    messagingSenderId: '398753978340',
    projectId: 'melon-d5a58',
    storageBucket: 'melon-d5a58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYMAlVEW-zs8gqsuglrB8Kszv0dxh3e4w',
    appId: '1:398753978340:ios:dad5744a96b0368cd1d9f1',
    messagingSenderId: '398753978340',
    projectId: 'melon-d5a58',
    storageBucket: 'melon-d5a58.appspot.com',
    iosClientId: '398753978340-8nsfreoucjehjn5q3ksvmp8s2qi3a8pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.water',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYMAlVEW-zs8gqsuglrB8Kszv0dxh3e4w',
    appId: '1:398753978340:ios:dad5744a96b0368cd1d9f1',
    messagingSenderId: '398753978340',
    projectId: 'melon-d5a58',
    storageBucket: 'melon-d5a58.appspot.com',
    iosClientId: '398753978340-8nsfreoucjehjn5q3ksvmp8s2qi3a8pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.water',
  );
}
